### ISSUE TITLE
Not working/connecting on Windows

### ISSUE THREAD

**Issue by gauthierguillaume** [levindecaro/streamdeck-ytmd#1]
Hi,

I am using the old streamdeck plugin from https://github.com/XeroxDev/YTMD-StreamDeck since years and it's working well,
but I can't understand why yours is not working at all.
I try a lot of settings without success.

I also try to get _`com.remote.ytmd0.log`_ but I can't find it anywhere.

Hope I can have some help to make it work.
Thanks a lot.

**Comment by levindecaro** [comment]
@gauthierguillaume 


> Logs are saved to disk per plugin in the folder ~/Library/Logs/ElgatoStreamDeck/ on macOS and %appdata%\Elgato\StreamDeck\logs\ on Windows. Note that the log files are rotated each time the Stream Deck application is relaunched.

Would you share your OS, Steamdeck,YTMD version information please.

**Comment by gauthierguillaume** [comment]
I'm on Windows 11 Professionnel, Version 22H2
Streamdeck: 6.3.0.18948
YTMD: v1.13.0

I'm on the logs folder but no _`com.remote.ytmd0.log`_
![image](https://github.com/levindecaro/streamdeck-ytmd-remote/assets/14924974/9f34a3e8-257f-46d6-bb07-b69f1ff53fa9)

This is what I get on the streamdeck:
![image](https://github.com/levindecaro/streamdeck-ytmd-remote/assets/14924974/cba55658-5dce-4f57-9392-947ff0d0b5f7)

**Comment by levindecaro** [comment]
@gauthierguillaume 

I found the problem are made by a mistake.

Please change the the line in the %appdata%\Elgato\StreamDeck\Plugins\com.remote.ytmd.sdPlugin\manifest.json from

```
"CodePath": "streamdeck-ytmd-remote",
```
to
```
"CodePathMac": "streamdeck-ytmd-remote",
"CodePathWin": "streamdeck-ytmd-remote.exe",
```

**Comment by gauthierguillaume** [comment]
It works very well now, Thanks a lot for the support !

Do you have some future update on it that you want to add, like customisation of settings, volume knob, etc... ?

Beside that thanks for the love you give to YTMD !

**Comment by levindecaro** [comment]
@gauthierguillaume 

glad that helps! I dont have specific plan on it yet but the upcoming ytmd v2, things will change by far, if you have idea of making it more friendly, please open a issue with [FEATURE] subject. I'll see if i can do it.
