### ISSUE TITLE
Not working, streamdeck-ytmd-remote.exe missing in plugins directory

### ISSUE THREAD

**Issue by Johaux** [levindecaro/streamdeck-ytmd#2]
Hi Levin,

My plugin is not working, it can connect to my YTMD, also I can see any log com.remote.ytmd0.log.

![image](https://github.com/levindecaro/streamdeck-ytmd-remote/assets/13618787/9837706d-c4f7-4afd-a4a1-efa7bcdb0d4e)

I have already configured the Manifest as indicated in the issue #1 but it don't work for me.

![image](https://github.com/levindecaro/streamdeck-ytmd-remote/assets/13618787/05b608df-f3fa-4497-b7c2-ceea2bd238e4)

I'm on Windows 11 Homel, V 22H2
Streamdeck: 6.3.0.18948
YTMD: v1.13.0

**Comment by levindecaro** [comment]
Hi @Johaux , I didn't get you, what you see on the streamdeck screen?

**Comment by Johaux** [comment]
![image](https://github.com/levindecaro/streamdeck-ytmd-remote/assets/13618787/f70a823d-f97d-43e8-a367-de6a3f1d19b9)

**Comment by levindecaro** [comment]
@Johaux , the problem likely caused by Antivirus false-positive scan, please try to uninstall v1.0.0 and install the v1.0.1 just released today.

https://github.com/levindecaro/streamdeck-ytmd-remote/releases/tag/v1.0.1

**Comment by Johaux** [comment]
Great!
It works now!

![image](https://github.com/levindecaro/streamdeck-ytmd-remote/assets/13618787/45d2bf9f-228f-4f5b-aa33-1c953e52c7f6)

Thanks for your support.
