### ISSUE TITLE
[FEATURE] YTMD v2 Support

### ISSUE THREAD

**Issue by joshuawowk** [levindecaro/streamdeck-ytmd#4]
**Feature**
Context: https://github.com/ytmdesktop/ytmdesktop/issues/1139

YTMDesktop (YTMD) has announced v2 (see above) and v2 is in active development. The changes of v2 include a backwards-incompatible companion server. This implies that the current version of the plugin would be incompatible with YTMD v2. This is a feature request for YTMD v2 support.

**Solution**
YTMD v2 compatibility of this plugin

**Alternatives**
N/A

**Anything else?**
[API documentation of the new companion server](https://github.com/ytmdesktop/ytmdesktop/wiki/v2-%E2%80%90-Companion-Server-API-v1)
Also, I'm hoping nobody minds that I copied this issue, nearly in its entirety, from here: https://github.com/XeroxDev/YTMD-StreamDeck/issues/85

**Comment by levindecaro** [comment]
@JoshuaWowk I'm working on it.

**Comment by joshuawowk** [comment]
Let me know if there's anyway I can help - joshua.wowk@hp-ne.com during the day

**Comment by levindecaro** [comment]
@JoshuaWowk thanks, the ytmd new version now using socket.io implementation, and none of usable go library are working for this case, if stick with restapi, there are rate limit that cannot exceed more than 1 call per 5sec. So, i need to workout the socket.io first before jump into the ytmd-remote.

**Comment by dansauve** [comment]
Any progress here?

**Comment by levindecaro** [comment]
@dansauve It is almost ready, I'm waiting for https://github.com/ytmdesktop/ytmdesktop/commit/983d53a3df9648ff8899d4ad54fae8889f25c902 release beforehand, since the like status is broken in current YTMD.

**Comment by dansauve** [comment]
@levindecaro Does the previous version still work with YTMD v1.13 or 1.14 nightly? I can't get it working... I can't find the "token" to input after enabling the YTMD server...

**Comment by levindecaro** [comment]
@dansauve YTMD remote v1.x still working with YTMD v1.13. When you have YTMD companion server enabled(Remote Control), the sub option called "Protect remote control with password".

After you enable it, it shown a 4 digit code, copy it  into YTMD encoder remote "YTMD token" setting. some time restart the steamdeck to make it work.

**Comment by levindecaro** [comment]
@dansauve @joshuawowk 

Please checkout the latest release for YTMD v2 support, it is working in progress to make it available in marketpalce, should you do install steamdeck plugin manually, you can download the latest one from now.
