### ISSUE TITLE
YTMD Not Appearing in Stream Deck

### ISSUE THREAD

**Issue by ha11sy** [levindecaro/streamdeck-ytmd#5]
Hi,

Not sure what has changed but YTMD shortcuts on stream deck stopped working for me, so as a part of troubleshooting, I removed the plugin and re-added it, it does not show on the list of available actions on the right to create the actions on buttons at all.  I have comfirmed that the plugin has been installed (and infact removed and re-added) to no avail, I have also completely removed Stream Deck software, and all associated %appdata% files to make it a clean wipe and started again, but not luck.

![SDPlugins](https://github.com/levindecaro/streamdeck-ytmd-remote/assets/155692687/2331a389-1a2e-4437-9a42-91fe551be344)

Any help appreciated.

**Comment by levindecaro** [comment]
@ha11sy looks your steamdeck do not have dial encoder available

**Comment by icessassin** [comment]
You may have had XeroxDevs Plugin which had been mistakenly merged/mislabeled as levins. So Xeroxs plugin was missing from the marketplace for abit, the issue has since been resolved by Elgato. Not too sure how the two plugins got combined as the UUID, Title and alot of things were different.

**Comment by levindecaro** [comment]
@icessassin Thanks for point out this, i'd no idea what's happening.
