### ISSUE TITLE
I was using 'ytmd encoder remote' very well.

### ISSUE THREAD

**Issue by Cherubyel3712** [levindecaro/streamdeck-ytmd#6]
We regret that the 'Companion Server' has been changed and unavailable due to the update of ytmd.
I hope it will be resolved quickly and available.
I was using 'ytmd encoder remote' very well.
We regret that the 'Companion Server' has been changed and unavailable due to the update of ytmd.
I hope it will be resolved quickly and available.
Thank you, sir

**Comment by levindecaro** [comment]
@Cherubyel3712 Yes, I'm working on it, but no timeline yet can be given yet, since the companion server part need to be completely rewrite.

**Comment by levindecaro** [comment]
@Cherubyel3712  It is almost ready, I'm waiting for https://github.com/ytmdesktop/ytmdesktop/commit/983d53a3df9648ff8899d4ad54fae8889f25c902 release beforehand, since the like status is broken in current YTMD.

**Comment by levindecaro** [comment]
@Cherubyel3712 

Please checkout the latest release for YTMD v2 support, it is working in progress to make it available in marketpalce, should you do install steamdeck plugin manually, you can download the latest one from now.
